# Generated by Django 4.2.5 on 2024-01-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_by', to='network.newpost'),
        ),
    ]
